[FAU-407] Initial preparation
RRZE-Webteam/FAU-Studium-Embed pull request #21
Opened 2024-04-26 19:14 UTC by amiut

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Chore

**What is the current behavior?** (You can also link to an open issue here)
https://inpsyde.atlassian.net/browse/FAU-407

**What is the new behavior (if this is a feature change)?**
- Added PR template
- Update package name to `rrze-webteam/fau-studium`

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

**Other information**:

2024-04-26 20:30 UTC, shvlv approved these changes

2024-04-29 06:40 UTC, tyrann0us requested changes
Please update `composer.lock`.

2024-04-29 06:40 UTC, tyrann0us commented on composer.json
> +    "name": "rrze-webteam/fau-studium-embed",
```suggestion
    "name": "rrze/fau-studium-embed",
```

2024-04-29 06:40 UTC, tyrann0us commented on composer.json
> +        "rrze-webteam/fau-studium-common": "*",
As per https://github.com/RRZE-Webteam/FAU-Studium-Common/pull/1#discussion_r1582594223.
```suggestion
        "rrze/fau-studium-common": "*",
```

2024-04-29 06:40 UTC, tyrann0us commented on package.json
> +  "name": "@rrze-webteam/fau-studium-embed",
Same here.
```suggestion
  "name": "@rrze/fau-studium-embed",
```

2024-04-29 06:55 UTC, o-samaras approved these changes
Left a minor comment but other than that, LGTM. Thanks.

2024-04-29 06:55 UTC, o-samaras commented on fau-degree-program-output.php
Since the package name is changing, let's rename the entry file to match or alternatively use `index.php`.

2024-04-29 06:57 UTC, amiut commented on fau-degree-program-output.php
This will cause plugins to be deactivated on all consuming website, I think we need an approval from the client to do this first

2024-04-29 08:42 UTC, tyrann0us approved these changes
LGTM. Thanks for working on this and incorporating the changes! 🙏🏽

2024-04-29 08:42 UTC, tyrann0us commented on fau-degree-program-output.php
We decided against renaming because it is out of scope.

2024-04-29 09:36 UTC, merged